colorScheme = "custom"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
enableImageOptimization = true
enableQuicklink = true
mainSections = ["hackthebox", "portswigger", "juiceshop", "vulnhub"]
robots = ""

[header]
  layout = "basic"
  logo = "logo.jpeg"
  logoDark = "logo.jpeg"
  logoWidth = 80
  logoHeight = 80

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  homepageImage = "logo.jpeg"
  showRecent = false
  showMoreLink = false
  cardView = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  sharingLinks = ["linkedin", "reddit", "twitter", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
  showDate = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  site = ""

[verification]
  google = ""
  bing = ""
  pinterest = ""
  yandex = ""
